server {
  server_name executable.it;
  root /var/www/executable.it;
  return 301 https://www.executable.it$request_uri;
}

server {
  server_name www.executable.it;
  root /var/www/executable.it/public;
  expires 5d;

  error_page 404 /404.html;
  location ~ '^/(404)\.html$' {
  }

  location = / {
    return 301 /it;
  }

  location ~ '^/index(\.html)?$' {
    return 301 /$is_args$args;
  }

  location ~ '^/(.*)\.html$' {
    return 301 /$1$is_args$args;
  }

  location / {
    index index.html;
    try_files $uri $uri.html $uri/ =404;
  }
}
