server {
	server_name executable.it;
	root /var/www/executable.it/dist;
	return 301 https://www.executable.it$request_uri;
}

server {
	server_name www.executable.it;
	root /var/www/executable.it/dist;
	expires -1;

	rewrite ^(.+)/$ $1 permanent;
	rewrite ^/(it|en)/(projects|contacts|about-me)/?$ /$1 permanent;

	error_page 404 /404.html;
	location ~ '^/(404)\.html$' {
	}

	location = / {
		return 301 /it;
	}

	location ~ '^/card(-bw)?$' {
		default_type text/plain;
		expires 5d;
	}

	location /assets { expires 5d; }
	location /fonts { expires 5d; }
	location /chunks { expires 5d; }
	location ~* \.js { expires 5d; }

	location / {
		index index.html;
		try_files $uri $uri.html $uri/index.html =404;
	}
}
